### ISSUE TITLE
希望web可以通过https访问

### ISSUE THREAD

**Issue by Amos-Dan** [jonssonyan/h-ui#1]
感谢作者的项目。
希望前端web界面通过tls里配置的密钥使用https访问，不然web界面感觉不是很安全。

**Comment by Amos-Dan** [comment]
另外，可以完善下readme，把./h-ui作为后台服务跑。

**Comment by Amos-Dan** [comment]
![1719214356508](https://github.com/jonssonyan/h-ui/assets/9195598/2d197526-8778-4204-ab87-4f673faf921a)
这个地方类似浏览器的tab，感觉不是很有必要。

**Comment by Amos-Dan** [comment]
可否考虑将账号管理页面的功能拆分一下，这里仅做节点管理，把管理员账号的功能放在系统设置里。

**Comment by Amos-Dan** [comment]
设备数量限制为0时，为不限制设备数量。
配额为0时，为不限制流量。
过期时间删除不填，为不限制过期日期。

**Comment by Amos-Dan** [comment]
账号管理中编辑更新时没有回显两个密码字段。希望可以回显下。

**Comment by pelacur595** [comment]
奇怪 大兄弟 你启动的时候 不会报http错误的那个吗

**Comment by Amos-Dan** [comment]
没有哈。是我没注意吗？

**Comment by jonssonyan** [comment]
> 奇怪 大兄弟 你启动的时候 不会报http错误的那个吗

肯定是配置的不对，没启动起来，看日志菜单

**Comment by jonssonyan** [comment]
> 另外，可以完善下readme，在非docker的物理机中手动安装时，把./h-ui如何作为后台服务跑起来给一个简单说明就更好了。例如给一个service unit的例子，可以通过systemd控制脚本。
> 
> ‘’‘ [Unit] Description=h-ui Service After=network.target Wants=network.target
> 
> [Service] Type=simple WorkingDirectory=/root/h-ui/ ExecStart=/root/h-ui/h-ui Restart=on-failure RestartSec=5s
> 
> [Install] WantedBy=multi-user.target ’‘’

改好了

**Comment by jonssonyan** [comment]
> ![1719214356508](https://private-user-images.githubusercontent.com/9195598/342242962-2d197526-8778-4204-ab87-4f673faf921a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDU5MzksIm5iZiI6MTcxOTI0NTYzOSwicGF0aCI6Ii85MTk1NTk4LzM0MjI0Mjk2Mi0yZDE5NzUyNi04Nzc4LTQyMDQtYWI4Ny00ZjY3M2ZhZjkyMWEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMTYxMzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGVmZTc5Zjk0ZGUwNDI5YWM0YjhhZWExNTVkNTIwZjhjYzBjZWVmMmIwYzhhNWI5MzZjOTYzZmM1YTU3NDlmZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EzwrElaciATZLV0SamisugSaGDqHmg2NinQQ9bdT9TI) 这个地方类似浏览器的tab，感觉不是很有必要。

有个有个齿轮的图标点击可以切换主题，支持关闭tag

**Comment by jonssonyan** [comment]
> 貌似设备数量修改不成功，有点bug。 另外，建议设置逻辑： 设备数量限制为0时，为不限制设备数量。 配额为0时，为不限制流量。 过期时间删除不填，为不限制过期日期。

1. 无法修改设备数量的问题，无法复现
2. 默认设备数6，不限制就999...直接拉满
3. 配额-1是不限制，可能文档里没有说明
4. 过期时间同样拉满

0或者不填这种特殊值，写代码的时候要考虑的比较多，手动把值选到最大吧，不费事

**Comment by jonssonyan** [comment]
> 感谢作者的项目。 希望前端web界面通过tls里配置的密钥使用https访问，不然web界面感觉不是很安全。

mark

**Comment by wxyShine** [comment]
> 奇怪 大兄弟 你启动的时候 不会报http错误的那个吗

你那是没启动成功才报的，因为你配置的不对导致没启动成功

**Comment by Amos-Dan** [comment]
> > 貌似设备数量修改不成功，有点bug。 另外，建议设置逻辑： 设备数量限制为0时，为不限制设备数量。 配额为0时，为不限制流量。 过期时间删除不填，为不限制过期日期。
> 
>     1. 无法修改设备数量的问题，无法复现
> 
>     2. 默认设备数6，不限制就999...直接拉满
> 
>     3. 配额-1是不限制，可能文档里没有说明
> 
>     4. 过期时间同样拉满
> 
> 
> 0或者不填这种特殊值，写代码的时候要考虑的比较多，手动把值选到最大吧，不费事

设备数量确实改不了啊。
无法复现吗？无法复现就算了。

**Comment by jonssonyan** [comment]
> 直接用大佬里面自带的证书申请

ACME的方式要等一段时间，证书申请下来之后才会启动，所以启动之后多刷几次页面。我加个提示吧。

**Comment by jonssonyan** [comment]
> 可否考虑将账号管理页面的功能拆分一下，这里仅做节点管理，把管理员账号管理功能放在系统设置里。

最好不要改，用户归用户，配置归配置，用户之间通过角色区分开就可以了，万一以后要加入用户注册功能，就很方便了。

**Comment by Amos-Dan** [comment]
> > 可否考虑将账号管理页面的功能拆分一下，这里仅做节点管理，把管理员账号管理功能放在系统设置里。
> 
> 最好不要改，用户归用户，配置归配置，用户之间通过角色区分开就可以了，万一以后要加入用户注册功能，就很方便了。你可以看下目前的表结构

对，就是这个意思，用户归用户，节点配置归节点配置。
1、目前面板的定位就是跟x-ui一样，单用户。
2、节点配置和用户注册是两个事儿。
3、例如：我要给我朋友整一个配置，我还需要给他设置登陆密码？

**Comment by Amos-Dan** [comment]
> > 貌似设备数量修改不成功，有点bug。 另外，建议设置逻辑： 设备数量限制为0时，为不限制设备数量。 配额为0时，为不限制流量。 过期时间删除不填，为不限制过期日期。
> 
>     1. 无法修改设备数量的问题，无法复现
> 
>     2. 默认设备数6，不限制就999...直接拉满
> 
>     3. 配额-1是不限制，可能文档里没有说明
> 
>     4. 过期时间同样拉满
> 
> 
> 0或者不填这种特殊值，写代码的时候要考虑的比较多，手动把值选到最大吧，不费事

在另一台机器上又部署了一下，还是改不了设备数量。

**Comment by jonssonyan** [comment]
> > > 貌似设备数量修改不成功，有点bug。 另外，建议设置逻辑： 设备数量限制为0时，为不限制设备数量。 配额为0时，为不限制流量。 过期时间删除不填，为不限制过期日期。
> > 
> > 
> > ```
> > 1. 无法修改设备数量的问题，无法复现
> > 
> > 2. 默认设备数6，不限制就999...直接拉满
> > 
> > 3. 配额-1是不限制，可能文档里没有说明
> > 
> > 4. 过期时间同样拉满
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 0或者不填这种特殊值，写代码的时候要考虑的比较多，手动把值选到最大吧，不费事
> 
> 在另一台机器上又部署了一下，还是改不了设备数量。

截个动图看下呢，什么系统？有什么报错提示么？

**Comment by jonssonyan** [comment]
> > > 可否考虑将账号管理页面的功能拆分一下，这里仅做节点管理，把管理员账号管理功能放在系统设置里。
> > 
> > 
> > 最好不要改，用户归用户，配置归配置，用户之间通过角色区分开就可以了，万一以后要加入用户注册功能，就很方便了。你可以看下目前的表结构
> 
> 对，就是这个意思，用户归用户，节点配置归节点配置。 1、目前面板的定位就是跟x-ui一样，单用户。 2、节点配置和用户注册是两个事儿。 3、例如：我要给我朋友整一个配置，我还需要给他设置登陆密码？

目前只有管理员可以登录，如果你要给人添加账号，只可以用管理员添加，同时设置密码。系统设置菜单对于配置表，比如Web 端口，也可能是邮箱管理，用户管理单独列一个菜单方便以后加入注册功能，用户应该不属于系统设置的范畴吧。

**Comment by Amos-Dan** [comment]
> > > > 貌似设备数量修改不成功，有点bug。 另外，建议设置逻辑： 设备数量限制为0时，为不限制设备数量。 配额为0时，为不限制流量。 过期时间删除不填，为不限制过期日期。
> > > 
> > > 
> > > ```
> > > 1. 无法修改设备数量的问题，无法复现
> > > 
> > > 2. 默认设备数6，不限制就999...直接拉满
> > > 
> > > 3. 配额-1是不限制，可能文档里没有说明
> > > 
> > > 4. 过期时间同样拉满
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 0或者不填这种特殊值，写代码的时候要考虑的比较多，手动把值选到最大吧，不费事
> > 
> > 
> > 在另一台机器上又部署了一下，还是改不了设备数量。
> 
> 截个动图看下呢，什么系统？有什么报错提示么？

Debian12
提示“成功”
但是再次进入后还是显示6，是不是没写到表里？
这个截图不知道行不行。
![image](https://github.com/jonssonyan/h-ui/assets/9195598/c08adb23-a884-4e02-a1d0-930a5c49b775)
![image](https://github.com/jonssonyan/h-ui/assets/9195598/329b67c6-78ae-440e-b001-a5a0630c432a)

**Comment by Amos-Dan** [comment]
> > > > 可否考虑将账号管理页面的功能拆分一下，这里仅做节点管理，把管理员账号管理功能放在系统设置里。
> > > 
> > > 
> > > 最好不要改，用户归用户，配置归配置，用户之间通过角色区分开就可以了，万一以后要加入用户注册功能，就很方便了。你可以看下目前的表结构
> > 
> > 
> > 对，就是这个意思，用户归用户，节点配置归节点配置。 1、目前面板的定位就是跟x-ui一样，单用户。 2、节点配置和用户注册是两个事儿。 3、例如：我要给我朋友整一个配置，我还需要给他设置登陆密码？
> 
> 目前只有管理员可以登录，如果你要给人添加账号，只可以用管理员添加，同时设置密码。系统设置菜单对于配置表，比如Web 端口，也可能是邮箱管理，用户管理单独列一个菜单方便以后加入注册功能，用户应该不属于系统设置的范畴吧。

作为产品，我设计的平台里，系统设置里一般必备的是：用户管理、角色管理、权限管理。
作为用户，我觉得有待优化的点是：
假如系统只有我一个管理员的前提下，我要为n个人创建节点的时候，我还要每次为他们设置登陆账号和密码，即使他们不能登陆？这种定位的话，只需要把授权管理放在系统管理中，可以修改管理员用户名密码即可，节点配置只关注Hy2的配置项。
假设之后要考虑开放普通用户注册，让普通用户登陆，那用户进来之后添加多个节点的时候，他们还需要重复设置登陆账户和密码？这种定位的话，必须给不同角色用户不同的菜单页面：在普通用户端：还是需要在系统管理中可以修改普通用户自己的账户和密码；在管理员端：增加用户管理页面，可管理注册的普通用户。

**Comment by Amos-Dan** [comment]
多谢大佬的更新！！！
请问可以加一个更新脚本的命令吗？后面方便对h-ui的更新等管理。

**Comment by jonssonyan** [comment]
@Amos-Dan 手动导出和到导入稳一点，就算搭建失败了，还有数据备份，重装之后重新开始随便折腾。升级脚本要做版本控制越往后积累的代码越多，先不考虑了。

**Comment by Amos-Dan** [comment]
> @Amos-Dan 手动导出和到导入稳一点，就算搭建失败了，还有数据备份，重装之后重新开始随便折腾。升级脚本要做版本控制越往后积累的代码越多，先不考虑了。

ok，明白。那备份哪个路径下的哪些文件呢？

**Comment by Amos-Dan** [comment]
大佬，是不是订阅还不支持v2rayN和Passwall？

**Comment by jonssonyan** [comment]
先做的Clash，v2rayN还没写完

**Comment by Amos-Dan** [comment]
> 先做的Clash，v2rayN还没写完



> 先做的Clash，v2rayN还没写完

OK。了解。
备份h-ui.db后直接覆盖也可以做到备份恢复吧？

**Comment by jonssonyan** [comment]
是的
