### ISSUE TITLE
后台节点复制到v2rayNG 我是bing.com 复制后不能导入，

### ISSUE THREAD

**Issue by josbu** [jonssonyan/h-ui#15]
复制的节点不带别名和 sni (比如我的bing.com)

**Comment by jonssonyan** [comment]
hysteria2 服务端配置文件和分享链接不存在别名的字段，别名时客户端的行为。参考：
https://v2.hysteria.network/zh/docs/advanced/Full-Server-Config/
https://v2.hysteria.network/zh/docs/developers/URI-Scheme/

sni 取的是 tls.acme.domains 的第一个

**Comment by josbu** [comment]
> hysteria2 服务端配置文件和分享链接不存在别名的字段，别名时客户端的行为。参考： https://v2.hysteria.network/zh/docs/advanced/Full-Server-Config/ https://v2.hysteria.network/zh/docs/developers/URI-Scheme/
> 
> sni 取的是 tls.acme.domains 的第一个

 也就是你面板解决不了是吧 那和以前我手动加吧

**Comment by josbu** [comment]
> hysteria2 服务端配置文件和分享链接不存在别名的字段，别名时客户端的行为。参考： https://v2.hysteria.network/zh/docs/advanced/Full-Server-Config/ https://v2.hysteria.network/zh/docs/developers/URI-Scheme/
> 
> sni 取的是 tls.acme.domains 的第一个
0.0.0.5 还是不行 还是没有bing.com  sni  这样少 了参数  v2rayNg不能识别不能导入，
第二就是我这用的别的服务器反代的，结果订阅链接是别的服务器网址不是HUI的IP，这样的话能不能HUI 用自己的IP 做订阅地址
