### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xxf185** [jonssonyan/h-ui#18]
订阅链接更新后端口为0

**Comment by jonssonyan** [comment]
具体复现步骤，截个图看看

**Comment by xxf185** [comment]
https://r.xxf186.asia:8081/hui/sysadmin.jbvghbbvgh   你可以试一下

**Comment by xxf185** [comment]
https://r.xxf186.asia:8081/hui/sysadmin.jbvghbbvgh

**Comment by xxf185** [comment]
订阅链接更新端口0

**Comment by jonssonyan** [comment]
1

**Comment by jonssonyan** [comment]
v0.0.6 fixed
