### ISSUE TITLE
http connection error

### ISSUE THREAD

**Issue by azadiazinjamigzare** [jonssonyan/h-ui#2]
Hi thanks for your develop 
I have error when enable the hy service from hysteria manage
Error: http connection error

![Screenshot_20240624_130837_Chrome](https://github.com/jonssonyan/h-ui/assets/167806621/146a67b4-6aa1-46b2-9e24-e04bd35437ea)

**Comment by jonssonyan** [comment]
![image](https://github.com/jonssonyan/h-ui/assets/46235235/745f81e3-68a0-4b45-8b18-24e25daf1d3d)
There may be something wrong with the certificate path you entered. It should be a file ending with .crt

**Comment by wxyShine** [comment]
建议 界面可以搞个生成自签证书 无需域名

**Comment by qhgy** [comment]
支持 越简单越好

**Comment by brightu** [comment]
same here.

**Comment by jonssonyan** [comment]
> > It is recommended that the interface can generate a self-signed certificate without the need for a domain name
> 
> Yes , i used that, but i received error again when enable service!😑🤔

There is a log menu on the left. Check the hysteria2 running log and send it here

**Comment by jonssonyan** [comment]
> 建议 界面可以搞个生成自签证书 无需自己的域名

Hysteria2 tls 设置里面已经内置了 acme 申请，面板不需要做什么
