### ISSUE TITLE
device limit not woeking

### ISSUE THREAD

**Issue by roozbehsat** [jonssonyan/h-ui#20]
![Screenshot (267)](https://github.com/user-attachments/assets/8d6ae871-5420-4047-9b8f-a5398caab233)
hi,
thanks for this nice panel
i test the limit device but its not working....

**Comment by twq168** [comment]
我也遇到了这个问题

**Comment by jonssonyan** [comment]
fixed https://github.com/jonssonyan/h-ui/releases/tag/v0.0.7
