### ISSUE TITLE
求增加一个自动重置流量功能

### ISSUE THREAD

**Issue by 634287319** [jonssonyan/h-ui#21]
VPS只有200G一个月，用超特别贵

**Comment by jonssonyan** [comment]
就是每个月定时重设用户使用的流量对吧

**Comment by 634287319** [comment]
> 就是每个月定时重设用户使用的流量对吧

是的

**Comment by jonssonyan** [comment]
added https://github.com/jonssonyan/h-ui/releases/tag/v0.0.7

**Comment by zhcxh** [comment]
应该添加每月底总流量重置以及总流量达到一定量后停用
