### ISSUE TITLE
not showing total number of users

### ISSUE THREAD

**Issue by b2never** [jonssonyan/h-ui#23]
Dear Developers
first of all thank you for a great panel
after I've created more than 10 users (default user's number shown each page is 10), if I change it to 20 or 30 or 50 it doesn't show me all users
even going to each pages doesn't work
![image](https://github.com/user-attachments/assets/1a71d2e6-dc76-4f33-917d-23646794f982)

**Comment by jonssonyan** [comment]
ok

**Comment by b2never** [comment]
Dear Sir
any update for this ?
can we get user's usage from another data-source(file, database, etc..)  as a workaround until this is fixed ?

**Comment by jonssonyan** [comment]
v0.0.6 fixed

**Comment by b2never** [comment]
thank you sir
great work

**Comment by b2never** [comment]
Great work
thank you
