### ISSUE TITLE
提示这个2个错误，不知道什么意思，求作者看看

### ISSUE THREAD

**Issue by slayercjc** [jonssonyan/h-ui#27]
![Snipaste_2024-07-25_11-24-22](https://github.com/user-attachments/assets/66ff80b9-2637-46ed-9de3-a42b16df4389)
![Snipaste_2024-07-25_11-24-32](https://github.com/user-attachments/assets/3f7e0f61-399e-4bd5-b430-11c0454c4890)

**Comment by Titanzxz** [comment]
1.防火墙关闭。2.短时间申请多次相同域名导致。

**Comment by jonssonyan** [comment]
上次我遇到这个问题的时候是换了ubuntu24解决的，具体什么原因还不知道
短时间内申请多次日志不是这个

**Comment by wangnimahahaha** [comment]
> 上次我遇到这个问题的时候是换了ubuntu24解决的，具体什么原因还不知道 短时间内申请多次日志不是这个

搬瓦工vps没有ipv6
debian 12 同样报错   ubuntu24 同样报错
docker手动部署，脚本都试过

**Comment by wangnimahahaha** [comment]
> 1.防火墙关闭。2.短时间申请多次相同域名导致。
我没有防火墙，没用acme,用的cloudflare的证书，一样报错

**Comment by Owen434** [comment]
443端口被占用了

**Comment by Owen434** [comment]
如题诚邀，一样碰到同样的问题。你可以查看443端口是否被占用，如果被占用请杀死。如果杀不死的话，就要看是否有其他固定的面板或者脚本绑定在该端口上。

**Comment by dts88** [comment]
![image](https://github.com/user-attachments/assets/646ea664-7fae-47a1-81ca-ea030ce316a5)

我也遇到相同的问题。 

关于上面提到关防火墙。难道不应该列清楚到底使用了哪些端口么？

**Comment by itdsgithub** [comment]
> 如题诚邀，一样碰到同样的问题。你可以查看443端口是否被占用，如果被占用请杀死。如果杀不死的话，就要看是否有其他固定的面板或者脚本绑定在该端口上。

我也遇到这样的问题，啥都没额外设置，直接运行就是http错误，因为我的服务器上还挂了小网站，443端口一直在用着，又不能给真的干掉，还用的宝塔面板，
这个问题我也不知道怎么解决，只能放弃不用咯。

**Comment by Weiitit** [comment]
是不是像图片一样在“Hysteria 管理”添加了伪装配置项，按图片一样把黄框里的80/443端口清空。如果已经有其他进程占用了80/443端口会导致Hysteria接管不了报错不能启动。

![2024-09-08](https://github.com/user-attachments/assets/4b0e0963-72ac-465e-aaa6-a27afe0e5880)

**Comment by Owen434** [comment]
> 是不是像图片一样在“Hysteria 管理”添加了伪装配置项，按图片一样把黄框里的80/443端口清空。如果已经有其他进程占用了80/443端口会导致Hysteria接管不了报错不能启动。
> 
> ![2024-09-08](https://private-user-images.githubusercontent.com/147345563/365433506-4b0e0963-72ac-465e-aaa6-a27afe0e5880.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTkxMTgsIm5iZiI6MTcyNTk1ODgxOCwicGF0aCI6Ii8xNDczNDU1NjMvMzY1NDMzNTA2LTRiMGUwOTYzLTcyYWMtNDY1ZS1hYWE2LWEyN2FmZTBlNTg4MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQwOTAwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWVkOTU5ZDNhMzQ5ZjhlZWVmYTc0Mjg5MGMyOTViY2E4YWQwMzc0MzRhYmIwNmE4OGRhNmJiODE2NmJiODliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yT5_ll09a9fSAwvAY9e4z296jWh3fVujeM8RLsRQDP8)

你可以试一试，如果不行的话，自行在网上查看一下端口检测命令。

**Comment by PillerC** [comment]
按照上面的要求做了，还是不可以使用，端口80/443也没有被占用
![image](https://github.com/user-attachments/assets/5d9578c1-128d-4b4d-a27e-1662e22cd497)

**Comment by yuancrazy** [comment]
搬瓦工报同样的问题日志；80 443都没占用，防火墙没开。root权限登录ssh 装也是一样报错

**Comment by yuancrazy** [comment]
搬瓦工报同样的问题日志；80 443都没占用，防火墙没开。root权限登录ssh 装也是一样报错

**Comment by yuancrazy** [comment]
> 默认的API端口：9999看有没有占用，或者换个api端口再试试
> 
> > 搬瓦工报同样的问题日志；80 443都没占用，防火墙没开。root权限登录ssh 装也是一样报错 看报错是和流量统计api相关的，不知道是不是这部分出的问题。能否自定义删除流量统计模块再测试下

端口换了一堆，一直是这个流量统计模块报问题。应该不是端口的问题。所以我想的是取消这个api，再试一下

**Comment by jonssonyan** [comment]
取消API就统计不到流量和用户认证等功能了

**Comment by yuancrazy** [comment]
> 取消API就统计不到流量和用户认证等功能了

明白。那确实不知道什么原因导致用不了。就默认4个配置填上就报错。也没有端口占用，没开防火墙。dock pull直接拉的镜像
