### ISSUE TITLE
acme方式申请证书成功，h-ui后台运行成功，导入链接无法使用

### ISSUE THREAD

**Issue by Titanzxz** [jonssonyan/h-ui#28]
acme方式申请证书成功，h-ui后台运行成功，导入链接无法使用，v2rayn测速时，提示the ssl connection could not be established see inner exception错误

**Comment by b2never** [comment]
maybe you have my issue.
first test with Sysadmin and see if it works
if yes, then consider that you have to put validity/quota on users so they can get connected
I had this (issue?!) before and i would get 403 error

**Comment by nicelic** [comment]
个人觉得使用acme感觉挺不好，hy2自带“偷盗”效果，找一个域名进行自签证书就可以达到偷盗效果。acme除了用到其他地方在这里是比较鸡肋的。
