### ISSUE TITLE
流量一天跑完2T！有人在RackNerd的VPS上用过这个面板吗？

### ISSUE THREAD

**Issue by wangchuanyes** [jonssonyan/h-ui#31]
不知道是面板问题还是RackNerd流量统计有问题，之前用非Hysteria2协议的时候RackNerd没有这种问题。装上H-UI后3T流量两天就用完了，但是实际上我根本没怎么用。

**Comment by jonssonyan** [comment]
服务器是不是被扫了？不是面板的问题，代码是公开的，不放心可以自己编译

**Comment by wangchuanyes** [comment]
> 服务器是不是被扫了？不是面板的问题，代码是公开的，不放心可以自己编译

好的，我重做系统，换个密码，再用试试
