### ISSUE TITLE
关于增加记录用户最后上线时间、优化限制设备连接数的功能

### ISSUE THREAD

**Issue by twq168** [jonssonyan/h-ui#33]
感谢能体验到这么优秀的H-UI项目。希望再优化面板，后台增加一项记录用户最后上线时间的功能，另外我在使用的过程中，发现限制设备连接功能没有效果，望修复这个问题。谢谢！

**Comment by jonssonyan** [comment]
added https://github.com/jonssonyan/h-ui/releases/tag/v0.0.7
