### ISSUE TITLE
设备在线问题

### ISSUE THREAD

**Issue by pelacur595** [jonssonyan/h-ui#36]
反馈一下子哈 不知道是不是客户端的问题
设备：iphone
然后客户端用的karing
连接上去以后后台不显示设备在线 但是实际已经在使用
也统计不到流量
然后创建的账号无法登入 提示密码错误 （实际上密码是正确的
版本是最新的0.0.7

**Comment by pelacur595** [comment]
重装以后 解决了 在线跟流量问题 
但是创建的账号还是无法登入

**Comment by jonssonyan** [comment]
只有系统管理员才可以登录，普通用户不能
