### ISSUE TITLE
创建其他用户登录,显示密码错误

### ISSUE THREAD

**Issue by Zstasi** [jonssonyan/h-ui#38]
![屏幕截图 2024-08-15 050048](https://github.com/user-attachments/assets/b6084739-75f7-47d2-a59e-42f61b3d300b)
我很肯定我没输错QAQ

**Comment by jonssonyan** [comment]
只有管理员才能登录系统，普通用户不能

**Comment by dts88** [comment]
> ![屏幕截图 2024-08-15 050048](https://private-user-images.githubusercontent.com/177674543/358005958-b6084739-75f7-47d2-a59e-42f61b3d300b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzg5NzUsIm5iZiI6MTcyNDEzODY3NSwicGF0aCI6Ii8xNzc2NzQ1NDMvMzU4MDA1OTU4LWI2MDg0NzM5LTc1ZjctNDdkMi1hNTllLTQyZjYxYjNkMzAwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQwNzI0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTY2ODcwOTk4NzkwMjc5YWU3NWU2NmJjNjAwZmY3MWFjZDUyMGEwZDAyZjlkY2RlZWYzZTEyODUwZDc0ZmM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AbEfUJKjlaDs_Z0YHF1tGB4_QG2Fy6FuZ2heNGYXt1s) 我很肯定我没输错QAQ

可以通过下载/上传JSON文件，来修改用户是user还是admin

**Comment by jonssonyan** [comment]
> 那你设置user的意义是？

方便后面扩展
