### ISSUE TITLE
Unraid docker中，网络类型为Host可以正常使用。当网络类型设置为bridge或其他自定义网络后，可访问面板，但客户端无法连接。

### ISSUE THREAD

**Issue by dts88** [jonssonyan/h-ui#41]
我在Unraid的docker中部署了H-UI，除了将H-UI的监听地址从443改成了4434之外，其他都是默认设置。并且docker中注明了所使用到的端口，路由器也设置了对应的端口转发。 

目前遇到的问题是，H-UI只能在HOST网络模式下正常运行，改为Bridge或者Custom后，H-UI面板可以正常访问，但客户端无法链接docker服务器端。

这在我使用的所有docker中，第一次遇到这种问题。Host网络与Bridge网络极为相似，按道理几乎没有任何区别。 Custom模式由于可以设置独立的IP甚至独立的网络环境，可能稍微复杂一些。但H-UI似乎在bridge下也无法正常运行，我怀疑是除了443, 8081, 9999之外，这个docker还是用了别的端口，且未在文档中说明。 麻烦大佬有空时看一下，谢谢！

> docker run
>   -d
>   --name='h-ui'
>   **--net='host'**
>   -e TZ="Asia/Singapore"
>   -e HOST_OS="Unraid"
>   -e HOST_HOSTNAME="UNRAID"
>   -e HOST_CONTAINERNAME="h-ui"
>   -e 'TCP_PORT_8081'='8081'
>   -e 'TCP_PORT_4434'='4434'
>   -e 'TCP_PORT_9999'='9999'
>   -l net.unraid.docker.managed=dockerman
>   -l net.unraid.docker.webui='https://[IP]:[PORT:8081]/'
>   -v '/mnt/user/appdata/h-ui/bin':'/h-ui/bin':'rw'
>   -v '/mnt/user/appdata/h-ui/data':'/h-ui/data':'rw'
>   -v '/mnt/user/appdata/h-ui/export':'/h-ui/export':'rw'
>   -v '/mnt/user/appdata/h-ui/logs':'/h-ui/logs':'rw'
>   --cap-add=NET_ADMIN 'jonssonyan/h-ui'
> d171da67872b35ebd4ae3059bdd2a12f27a104003f0213308b7ea8b1a53b986c
> 
![image](https://github.com/user-attachments/assets/48d50bd9-3dbe-424f-8b4b-ba08c55b08b4)
![image](https://github.com/user-attachments/assets/947ad9f2-fe75-4166-8eae-7c842339e2c9)

**Comment by dts88** [comment]
不好意思，看上面docker跑的命令时，突然灵光一现找到问题了。是443监听端口跑的UDP，并非TCP。稍作修改后，这个Docker已经可以在Bridge模式下正常运行。 


> docker run
>   -d
>   --name='h-ui'
>   **--net='bridge'**
>   -e TZ="Asia/Singapore"
>   -e HOST_OS="Unraid"
>   -e HOST_HOSTNAME="UNRAID"
>   -e HOST_CONTAINERNAME="h-ui"
>   -l net.unraid.docker.managed=dockerman
>   -l net.unraid.docker.webui='https://[IP]:[PORT:8081]/'
>   -p '8081:8081/tcp'
>   **-p '4434:4434/udp'**
>   -p '9999:9999/tcp'
>   -v '/mnt/user/appdata/h-ui/bin':'/h-ui/bin':'rw'
>   -v '/mnt/user/appdata/h-ui/data':'/h-ui/data':'rw'
>   -v '/mnt/user/appdata/h-ui/export':'/h-ui/export':'rw'
>   -v '/mnt/user/appdata/h-ui/logs':'/h-ui/logs':'rw'
>   --cap-add=NET_ADMIN 'jonssonyan/h-ui'
> 9055a1af17fc5d8fe0cf612895ee11aee22126a4d091f4b88f8afb7261d32bf7

**Comment by jonssonyan** [comment]
9999监听的是127.0.0.1，不需要开放。

面板端口、代理端口、如果是端口跳跃还有端口跳跃的端口，这些开放就可以

**Comment by dts88** [comment]
好的，谢谢！
