### ISSUE TITLE
账户管理面板缺少用户、管理员的设置选项

### ISSUE THREAD

**Issue by dts88** [jonssonyan/h-ui#42]
账户管理面板缺少用户、管理员的设置选项。只能通过json文件修改。

另外，目前的H-UI界面，只有admin可以登录，我不清楚通常是否允许user登录这个界面呢？ （不重要，只是好奇，其他面板我也没用过）

**Comment by jonssonyan** [comment]
目前现在规则就是这样，只有管理员可以登录
