### ISSUE TITLE
无法设置QUIC参数

### ISSUE THREAD

**Issue by Sakamakiiizayoi** [jonssonyan/h-ui#43]
无法设置QUIC参数，保存后参数都变为0
![image](https://github.com/user-attachments/assets/05467e6c-afc9-4ec7-ba3c-9ad53d98c866)

**Comment by jonssonyan** [comment]
版本多少？复现步骤是什么？

**Comment by Sakamakiiizayoi** [comment]
h-ui版本0.0.7 h2版本2.5.1 系统Debian11
复现步骤 添加quic配置项后修改默认数值，保存后修改的值变为0，不修改的默认值则不会变0
![image](https://github.com/user-attachments/assets/72aa1c46-681e-4374-bca0-334c6c8332d0)

**Comment by Sakamakiiizayoi** [comment]
除了maxidletimeout项外其他项修改默认值保存后都会变0

**Comment by jonssonyan** [comment]
fixed https://github.com/jonssonyan/h-ui/releases/tag/v0.0.8
用一键安装脚本更新即可
