### ISSUE TITLE
断流有点严重

### ISSUE THREAD

**Issue by maajiko** [jonssonyan/h-ui#46]
加了端口跳跃，还是经常断流

**Comment by Sakamakiiizayoi** [comment]
这个你应该问GFW 最近我也在摸索 发现好像莫得办法 无差别封杀大流量udp

**Comment by jonssonyan** [comment]
断流问题，到 Hysteria 仓库下面提

**Comment by Sakamakiiizayoi** [comment]
> 加了端口跳跃，还是经常断流

感觉不同线路的udp限制策略也不一样，最近在用日本软银线路 30005端口不开混淆不开端口跳跃，这几天用下来都没遇到限速和封端口，你可以用这个配置试试
