### ISSUE TITLE
是否可以增加telegram bot 机器人支持

### ISSUE THREAD

**Issue by kakagood6** [jonssonyan/h-ui#47]
是否可以增加telegram bot 机器人支持，这样更便于管理，管理员通过机器人直接操作网页实现的相关功能，  客户绑定机器人后可以直接获取订阅地址即剩余时间和流量。

**Comment by jonssonyan** [comment]
可以，但是近期没计划写

**Comment by jonssonyan** [comment]
实现了一个最初版本，后面慢慢加，先占坑位
https://github.com/jonssonyan/h-ui/releases/tag/v0.0.10
