### ISSUE TITLE
SNI

### ISSUE THREAD

**Issue by Ilaprgg2** [jonssonyan/h-ui#5]
Hi
Thank you for your excellent work on this project. I've noticed two potential improvements

1. SNI field: Currently missing, but necessary for proper client-side functionality.
2. Allow Insecure Option: Would be useful for bypassing certificate validation in certain scenarios.

Thanks again for your time and effort

**Comment by jonssonyan** [comment]
ok

**Comment by jonssonyan** [comment]
h-ui v0.0.3, url already supports SNI and Insecure options
