### ISSUE TITLE
流量统计不准，望能修复

### ISSUE THREAD

**Issue by Weiitit** [jonssonyan/h-ui#51]
作者你好，使用你开发的Hysteria2面板几天很不错，先谢谢你！在使用过程中发现了一些问题和建议，希望有空时能修复和改善：

1. 流量统计不准，在已使用面板的一天时间里同一用户在电脑客户端v2rayN统计使用了1.5G(确定电脑客户端不会错），面板也正常显示用户在线但只统计使用了560M不到，也想过可能是统计有延迟，但过去了一天也没有正常。流量统计是很实用的功能，希望修复！

2. 连接密码，真正的连接密码 = 用户名.连接密码，面板上没有任何提示，虽然可以通过“节点 URL”知道真正的连接密码，但对于很多手搓客户端不通过导入的人来说就是恶梦，会以为设的连接密码就是真正的连接密码。

3. 配额，以大家的一般认知“配额”设为0是无限∞，但这里设为0真的是0流量不能用了(知道设-1才是无限∞)，也没有提示有点反常识；

4. 过期时间，没有无限期选项，例如可以修改+提示“留空表示永不过期”；

5. “Hysteria 管理”里添加了伪装配置项后，很多人只用到上面的masquerade.type和masquerade.proxy.url，不用masquerade.listenHTTP和masquerade.listenHTTPS，但2个选项默认填上了80/443端口，最好默认不填上另加提示，懂的人有用到自然会填，如有其他进程占用80/443端口会导致Hysteria报错不能启动，不会看日志的人不会知道是这里出问题。

**Comment by jonssonyan** [comment]
1. 流量不准，待验证，可以暂时设置流量倍率来控制，设置一个自己觉得合适的值
2. 连接密码需要唯一，所以引入用户名来保证唯一性，没有想到特别好的方案，如果你有更好的方案可以提
3. 0有特殊含义，代表账户没有流量不可用（比如流量重设就是把流量设置为0），和无穷大要区分，不能混用，可以加个提示帮助大家理解
4. 过期时间即使设置为永不过期，存储的时候还是会给一个值，比如100年之后，可以在选择时间的时候加一个永久的快捷选项
5. 既然这样那就去掉吧，所有配置都是严格按照hysteria官方文档来的，值也是文档的默认值

**Comment by Weiitit** [comment]
1. 倍率控制前提是有规律，但根本没有规律可言，重新统计了一下如下图，左边是v2rayN，右边是面板，下载差了6倍多，上次统计是3倍左右。
![速度](https://github.com/user-attachments/assets/0627ecee-439f-4665-ba64-e202280d55d7)

2. 密码像用户名一样查重，重复不能保存。暂时是单管理员管理也不拍其他用户改密码撞知密码。

其他也只是一些注释意见，谢谢回复！

**Comment by jonssonyan** [comment]
密码很少有去重的， 一般都是用户名去重。不然很大概率123456简单密码都会重复

**Comment by jonssonyan** [comment]
> 1.能否可以随时查看连接密码？ 现在返回后无法再看到连接密码. 2. 能否增加一个生成连接密码按钮 例如生成一个自定义多少位和类型密码, 我觉得20位以上密码不如意重复.

1. 连接密码，在你复制订阅url/节点url的时候能明文展示，另外，连接密码格式是{登录用户名}.{登录密码}，比如：默认的连接密码就是sysadmin.sysadmin（登录的用户名和密码都是sysadmin）
2. 自定义的连接密码肯定会有重复的情况，特别是在样本数量大的情况下，目前方案就是通过用户名和密码通过.连接来去重，同时方便好记，并且.在分享链接中暂时还未发现有不兼容的情况

**Comment by jonssonyan** [comment]
不能，任何密码不能明文显示，数据库里面也是加密的

**Comment by jonssonyan** [comment]
> 不能，任何密码不能明文显示，数据库里面也是加密的

不能，任何密码不能明文显示，数据库里面也是加密的

**Comment by aishlai** [comment]
我最近也发现了，确实流量不准

**Comment by jonssonyan** [comment]
> 我最近也发现了，确实流量不准

系统设置里面调整倍率，默认倍率是1

**Comment by aishlai** [comment]
> > 我最近也发现了，确实流量不准
> 
> 
> 
> 系统设置里面调整倍率，默认倍率是1

其实我更关注是哪个环节出现了错误，是你从统计接口拿数据出了问题？还是再累计的时候出现的错误？逻辑上这两个阶段都不应该出现问题？

**Comment by aishlai** [comment]
> > 我最近也发现了，确实流量不准
> 
> 
> 
> 系统设置里面调整倍率，默认倍率是1

我用的HY的版本是2.6，H-ui的版本是0.0.16

**Comment by jonssonyan** [comment]
@aishlai 

你的用户量是多大？系统运行日志贴出来看看

**Comment by aishlai** [comment]
> @aishlai 
> 
> 
> 
> 你的用户量是多大？系统运行日志贴出来看看

用户量不大，就10个左右，而且主要就我自己产生流量，我起初发现VPS提供商的流量统计大幅超过了我的hy2的，后来我排查到可能是由于pt导致暴露了代理地址导致，然后修改了防火墙规则解决了，但是每天流量的增速还是不对，后来我用vnstat统计了eth0的5分钟级流量，在5分钟内，我访问了8k的油管视频，发现和h-ui统计差异很大，vnstat统计的数据和VPs提供商的大体相同

**Comment by aishlai** [comment]
> @aishlai 
> 
> 
> 
> 你的用户量是多大？系统运行日志贴出来看看
> 
> 
> 
> 代码位置：https://github.com/jonssonyan/h-ui/blob/0e5bcbe9681573d0a7e717911eb608c5160ff415/service/cron.go#L77

![image](https://github.com/user-attachments/assets/a0b7bf8c-e0ed-4ca1-90f2-d3f4cd76d379)

最近的两个error，是昨天产生的，那时候应该是重启了hy2服务导致的，后续就没有error了
