### ISSUE TITLE
证书问题

### ISSUE THREAD

**Issue by DamonLee35** [jonssonyan/h-ui#53]
开发者您好，请问一下我给ipv4加了证书，使用ipv6连接会加密吗？

**Comment by jonssonyan** [comment]
我觉得可以，只要你设置了证书选项，如果域名不是一个，要设置允许不安全，可以在 hysteria 提 issue 确认一下

**Comment by DamonLee35** [comment]
不行，昨天试了下晚上ipv6就被封了
