### ISSUE TITLE
hysteria管理中配置文件无法保存

### ISSUE THREAD

**Issue by knightfantasy** [jonssonyan/h-ui#54]
docker compose部署

services:
  h-ui:
    image: jonssonyan/h-ui
    cap_add:
      - NET_ADMIN
    container_name: h-ui
    restart: always
    network_mode: host
    volumes:
      - ./bin:/h-ui/bin
      - ./data:/h-ui/data
      - ./export:/h-ui/export
      - ./logs:/h-ui/logs
    environment:
      TZ: Asia/Shanghai

hysteria管理中点击保存，提示 invalid
{"code":50001,"type":"no","message":"invalid","data":null}

导入配置文件，会报 500 Internal Server Error

测试发现当TLS选tls点击保存可通过，选acme填入内容无法保存

**Comment by jonssonyan** [comment]
更新了v0.0.9版本，试试，解决这个问题了
