### ISSUE TITLE
能否像s-ui那样添加多个hysteria节点

### ISSUE THREAD

**Issue by Hawyan999** [jonssonyan/h-ui#55]
能否像s-ui那样添加多个hysteria节点，一个用户有多个hysteria节点

**Comment by jonssonyan** [comment]
不能
1. 改动较大
2. 服务器资源是固定的，本质上这样做没有意义
3. s-ui 基于 sing-box，支持多个入站，但是本质还是一个 sing-box 服务端，hysteria 入站只支持 hysteria 一种协议，有区别

可以尝试搭建多个hui，设置不同的监听端口

**Comment by Hawyan999** [comment]
理解了，非常感谢！！

jonssonyan ***@***.***> 于2024年9月18日周三 16:56写道：
