### ISSUE TITLE
安装完无法登录是为啥？

### ISSUE THREAD

**Issue by monobo1989** [jonssonyan/h-ui#58]
面板可以打开，但是输入默认用户名和密码后，点登录没有反应。

docker ps后如图：https://pic.rmb.bdstatic.com/bjh/241004/e3e37d06c458870ed72b7596b87d18aa6676.png

**Comment by jonssonyan** [comment]
F12看下控制台，console 控制台报错还是接口报错。从截图看，容器运行正常

**Comment by monobo1989** [comment]
> F12看下控制台，console 控制台报错还是接口报错。从截图看，容器运行正常

这个样子：https://s21.ax1x.com/2024/10/05/pA8JE4I.jpg 不晓得咋办。。

**Comment by jonssonyan** [comment]
> > F12看下控制台，console 控制台报错还是接口报错。从截图看，容器运行正常
> 
> 可以登录了。可是又遇到问题。日志如下： HY日志：https://pic.rmb.bdstatic.com/bjh/241005/908687f805fba33398bc95978def2bf7797.png 系统日志：https://pic.rmb.bdstatic.com/bjh/241005/2b81e42961989729c37b53ce9f6f2f778912.png
> 
> 针对HY日志，证书路径没问题，我填的是/root/hui.103006.xyz.crt和/root/hui.103006.xyz.key 证书在服务器的位置：https://pic.rmb.bdstatic.com/bjh/241005/d16af7a44d6176aa7a4fbb2ad1861bc93370.png 权限也给了。 针对系统日志， 是不是端口被占用了，但是我在VPS上咋查不到：https://pic.rmb.bdstatic.com/bjh/241005/f4fb0a3d27015a5571df22830d417cf86566.png

HY日志可以看到，证书文件没找到，如果搭建方式是 Docker 需要将证书文件上传到映射文件夹内，比如 /h-ui/bin

**Comment by monobo1989** [comment]
> > > F12看下控制台，console 控制台报错还是接口报错。从截图看，容器运行正常
> > 
> > 
> > 可以登录了。可是又遇到问题。日志如下： HY日志：https://pic.rmb.bdstatic.com/bjh/241005/908687f805fba33398bc95978def2bf7797.png 系统日志：https://pic.rmb.bdstatic.com/bjh/241005/2b81e42961989729c37b53ce9f6f2f778912.png
> > 针对HY日志，证书路径没问题，我填的是/root/hui.103006.xyz.crt和/root/hui.103006.xyz.key 证书在服务器的位置：https://pic.rmb.bdstatic.com/bjh/241005/d16af7a44d6176aa7a4fbb2ad1861bc93370.png 权限也给了。 针对系统日志， 是不是端口被占用了，但是我在VPS上咋查不到：https://pic.rmb.bdstatic.com/bjh/241005/f4fb0a3d27015a5571df22830d417cf86566.png
> 
> HY日志可以看到，证书文件没找到，如果搭建方式是 Docker 需要将证书文件上传到映射文件夹内，比如 /h-ui/bin

谢谢，移动证书位置，就可以用了。
