### ISSUE TITLE
请问节点的密码都是sysadmin.sysadmin , 不能修改吗?

### ISSUE THREAD

**Issue by sunyuanxin** [jonssonyan/h-ui#62]
尝试修改H-UI 账户的用户名和密码,但是节点url 显示 密码还是 sysadmin.sysadmin

**Comment by josbu** [comment]
我就是不能自定义密码直接不用了 那个密码用openclash 订阅 影响识别

**Comment by jonssonyan** [comment]
有两个密码，一个是登录密码，一个是链接密码。节点密码是链接密码
