### ISSUE TITLE
新增账户无法连接

### ISSUE THREAD

**Issue by liuxyon** [jonssonyan/h-ui#63]
管理员身份新增的用户，客户端扫描完二维码后无法连接. 测试新增几个账户都无法使用.

**Comment by jonssonyan** [comment]
系统日志和hy2日志贴一下

**Comment by jonssonyan** [comment]
感觉你的服务器DNS有问题

**Comment by jonssonyan** [comment]
服务器请求代理接口都失败了，手动安装试试，不行就试试IPv4吧

**Comment by jonssonyan** [comment]
DD系统吧，试试其他操作系统，比如CentOS 8，Debian 11，Ubuntu 22
