### ISSUE TITLE
不能使用ip4 访问

### ISSUE THREAD

**Issue by xuegodot** [jonssonyan/h-ui#64]

**Comment by jonssonyan** [comment]
配置看看

**Comment by xuegodot** [comment]
ip4 和ip6都有  安装也正常。可是我的网络不支持ip6访问。所以安装之后。打不开面板。我看设置里面也没有ip4和ip6的切换。

**Comment by jonssonyan** [comment]
ipv4 使用应该是没问题的，我之前测试过PC端ipv6不行，客户端用的是v2rayN，移动端用的小火箭支持ipv6使用，具体什么原因还没细看
