### ISSUE TITLE
伪装代理网站失败

### ISSUE THREAD

**Issue by DamonLee35** [jonssonyan/h-ui#66]
使用伪装功能代理网站，访问我的域名无法跳转目标网址，提示错误代码502，如图所示<img width="789" alt="image" src="https://github.com/user-attachments/assets/1e3efd95-6a7b-4941-ba17-8b00f7a1c9e0">

**Comment by DamonLee35** [comment]
还有就是我用的自签名证书，开启sni验证后无法连接成功，确认客户端sni网站和证书一致

**Comment by jonssonyan** [comment]
配置贴出来看看，关键信息打码

**Comment by DamonLee35** [comment]
如图![IMG_20241019_130153](https://github.com/user-attachments/assets/bb70f49c-ef01-48dc-8992-d903c95f02b8)

**Comment by jonssonyan** [comment]
看不出来，你到hysteria2仓库下面提问吧，面板负责生成hy2配置，如果配置字段没生成错就不是面板的问题
https://github.com/apernet/hysteria/issues

**Comment by DamonLee35** [comment]
好的谢谢
