### ISSUE TITLE
容器启动的hysteria, 用另一个容器启动 h-ui, 面板怎么连接到 hysteria?

### ISSUE THREAD

**Issue by qiref** [jonssonyan/h-ui#68]
<img width="874" alt="image" src="https://github.com/user-attachments/assets/aefce85a-4503-4afe-9e46-787d0763e5a8">
<img width="383" alt="image" src="https://github.com/user-attachments/assets/26804b0d-257a-4fb9-9512-b580bb435bf3">

**Comment by jonssonyan** [comment]
不支持，这是一个单体应用
