### ISSUE TITLE
http connection error

### ISSUE THREAD

**Issue by xingkaijun** [jonssonyan/h-ui#71]
用docker部署的，启动节点的时候报错http connection error，

系统日志：

error | Hysteria2 OnlineUsers err: Get "http://127.0.0.1:9999/online": dial tcp 127.0.0.1:9999: connect: connection refused | 2024-10-27 10:45:18
error | Hysteria2 OnlineUsers err: Get "http://127.0.0.1:9999/online": dial tcp 127.0.0.1:9999: connect: connection refused | 2024-10-27 10:45:18

hysteria日志：

error | 2024-10-27T10:48:46+08:00 [34mINFO[0m acme_client trying to solve challenge {"identifier": "hyarm.11111.xyz", "challenge_type": "http-01", "ca": "https://acme.zerossl.com/v2/DV90"} | 2024-10-27 10:48:46
error | 2024-10-27T10:48:45+08:00 [34mINFO[0m done waiting on internal rate limiter {"identifiers": ["hyarm.11111.xyz"], "ca": "https://acme.zerossl.com/v2/DV90", "account": "testtest@gmail.com"} | 2024-10-27 10:48:45
error | 2024-10-27T10:48:45+08:00 [34mINFO[0m waiting on internal rate limiter {"identifiers": ["hyarm.11111.xyz"], "ca": "https://acme.zerossl.com/v2/DV90", "account": "testtest@gmail.com"} | 2024-10-27 10:48:45
error | 2024-10-27T10:48:45+08:00 [34mINFO[0m obtain obtaining certificate {"identifier": "hyarm.11111.xyz"} | 2024-10-27 10:48:45
error | 2024-10-27T10:48:45+08:00 [34mINFO[0m obtain lock acquired {"identifier": "hyarm.11111.xyz"} | 2024-10-27 10:48:45
error | 2024/10/27 10:48:45 [INFO][FileStorage:my_acme_dir] Lock for 'issue_cert_hyarm.11111.xyz' is stale (created: 2024-10-27 10:33:44.385403739 +0800 CST, last update: 2024-10-27 10:48:35.385597452 +0800 CST); removing then retrying: my_acme_dir/locks/issue_cert_hyarm.11111.xyz.lock | 2024-10-27 10:48:45

**Comment by jonssonyan** [comment]
三个方案
- 刷页面观察
- 重启服务器
- 换个耳机域名

**Comment by AGou-ops** [comment]
估计是你hysteria配置没配好，我是TLS证书里面没填自签证书，也会有这个报错.

**Comment by nicelic** [comment]
使用docker我也报错，但是相同的步骤安装时，选择1安装在系统没有错，感觉少了一些访问权限导致，我并没有进行排查。

**Comment by guojianrongtj** [comment]
使用docker安装遇到同样问题，不知道如何解决

**Comment by jonssonyan** [comment]
> 使用docker安装遇到同样问题，不知道如何解决

自动申请证书需要临时开放80或者443端口，申请的时候会暂时连接不上或者等一段时间刷新页面看，日志里面会显示申请的过过程

**Comment by guojianrongtj** [comment]
> > 使用docker安装遇到同样问题，不知道如何解决
> 
> 自动申请证书需要临时开放80或者443端口，申请的时候会暂时连接不上或者等一段时间刷新页面看，日志里面会显示申请的过过程
我看证书已经成功申请到了，但是tls填好后无法启动hy2
![image](https://github.com/user-attachments/assets/47f83412-ab73-4e97-8a02-86b96a162b27)

![image](https://github.com/user-attachments/assets/a23decdf-7aef-4a9e-8e44-c6fd75d9b92a)

**Comment by jonssonyan** [comment]
masquerade 配置错了，把错误日志复制到翻译软件就知道了

**Comment by guojianrongtj** [comment]
> masquerade 配置错了，把错误日志复制到翻译软件就知道了 @guojianrongtj

谢谢，我添加了一个www.bing.com的伪装，把这个伪装去掉已经成功运行，至于为什么还不清楚。
