### ISSUE TITLE
关于npm申请的pem证书，没有办法使用，http error

### ISSUE THREAD

**Issue by Whys8182** [jonssonyan/h-ui#74]
该如何解决这个问题呢，我的vps搭建了npm，并且申请了证书，按照视频的教程走下来，才发现没有单纯的key证书，只有pem格式的证书，不知道是否有办法解决，使用npm呢？

另外，我有几个建议，希望在代码上，尤其是选项和说明，能够使用中文显示。英文还是有点不友好的。

最后，强烈希望写一个官方的docker-compose代码放在github上面。

**Comment by Whys8182** [comment]
HUI不像SUI、XUI一样支持npm的pem证书，是真的麻烦，希望能支持一下，至于歇斯底里，倒不知道怎么解决了

**Comment by jonssonyan** [comment]
hysteria不支持，面板也没有办法，可以到hysteria仓库下提issue，本质上面板只是是提供了一个可视化的页面方便生成启动时候的配置文件
英文是全球通用语言，看不懂有谷歌翻译，装好之后页面上可以中英文切换
docker-compose文件在这里：https://github.com/jonssonyan/h-ui/blob/main/docker-compose.yml

**Comment by Whys8182** [comment]
好的，docker-compose后来我有找到了，hysteria倒是不容易。只是佬，面板证书问题也不行吗？英文其实是看得懂的，只是觉得既然是给国人用的面板，没必要设置一个英文，外国友人都有专门出去的手机卡，实际上用不上这些面板。所以实在建议能以中文的选项呈现。x-ui和s-ui这点都挺好的。

**Comment by jonssonyan** [comment]
没必要
