### ISSUE TITLE
修改web端登录密码的配置文件在哪呀

### ISSUE THREAD

**Issue by liuzhen225588** [jonssonyan/h-ui#79]
前端密码死活登录不进去，想在后台重置一下，找不到配置文件，求助

**Comment by jonssonyan** [comment]
https://github.com/jonssonyan/h-ui/blob/main/docs/FAQ_ZH.md#%E5%91%BD%E4%BB%A4%E8%A1%8C

脚本里面有选项可以重设用户名和密码
