### ISSUE TITLE
Centos Stream 9使用安装脚本时显示不支持

### ISSUE THREAD

**Issue by TobishiroGinko** [jonssonyan/h-ui#82]
/dev/fd/63: line 125: [[: package centos-release is not installed: syntax error in expression (error token is "centos-release is not installed")
Unsupported CentOS version: package centos-release is not installed. Only supports CentOS 6+.
运行dnf install centos-release后显示
Last metadata expiration check: 0:00:31 ago on Sat 16 Nov 2024 06:35:27 AM EST.
Package centos-stream-release-9.0-26.el9.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!

**Comment by TobishiroGinko** [comment]
Centos Stream 9 的包名应该是centos-stream-release，rpm -q --queryformat '%{VERSION}' centos-release获取不到版本(

**Comment by TobishiroGinko** [comment]
同时我在使用时发现脚本重置管理员密码时会出现
ERRO[0000] sqlite open err: unable to open database file: out of memory (14) 
sqlite open err
原因是缺少环境变量，已提交pr

**Comment by jonssonyan** [comment]
已合并
