### ISSUE TITLE
新增的用户不起作用

### ISSUE THREAD

**Issue by nicelic** [jonssonyan/h-ui#84]
账户管理那里，默认使用的是admin的用户，新增的用户为user用户，新增的用户名不可与admin相同，密码相同。
新增用户后，Hysteria 管理那里并没有 选择 “用户” 的地方，即配置hy2不可选择admin或者user的哪一个作为用户，也找不到配置或者选择新用户的功能的地方。退出面板后使用设定的新用户进行登录则是报错的。这个我确实找不到配置的地方。

以没有配置新用户为前提，是否可以将 “Hysteria 管理” 功能从主页面删除，做成居中的浮动面板，并在每一个用户处（admin、user、user1等）添加 “Hysteria 管理”按钮，点击 “Hysteria 管理” button按钮就会调出配置面板进行单个用户的hy2配置，点击保存即可对应每个用户。

**Comment by jonssonyan** [comment]
账户管理那块的数据都是hy2的用户
只有系统管理员可以登录
面板是一个hysteria节点，多用户，最终是生成一个hy2启动的配置文件
