### ISSUE TITLE
acme 无法生成证书，h-ui能通过https://正常登录，hysteria2也显示启动，但节点无法连接

### ISSUE THREAD

**Issue by zhenxiwen** [jonssonyan/h-ui#85]
在h-ui面板设置里，采用acme 域名申请证书，acme 无法生成证书，h-ui能通过https://域名正常登录，hysteria2也显示启动，vps防火墙已经关闭，但节点无法连接
ssh连接vps，查看显示没有证书目录，多次尝试都是一样：
root@instance-20231105-2241:/etc# cd /usr/local/h-ui
-bash: cd: /usr/local/h-ui: No such file or directory

**Comment by jonssonyan** [comment]
acme 申请证书的时候要临时监听80和443，检查看是不是这个原因
面板里面有日志菜单，要不你贴个日志看看？

**Comment by charliecaiyu** [comment]
唉，我也是DOCKER 安装 ，生成不了证书。
