### ISSUE TITLE
提几个小建议

### ISSUE THREAD

**Issue by hkfires** [jonssonyan/h-ui#86]
1、端口跳跃对于IPv4地址生效，但是对于IPv6地址没有生效
2、希望能够增加ACL调整位置的功能，目前ACL要调整位置要全部删除后重写
3、同理，现在ACL也不能编辑修改，只能删除重加，而删除重加就会变更ACL规则的顺序

**Comment by jonssonyan** [comment]
1. 默认是同时转发ipv4和ipv6，看一下转发工具用的是nft还是iptables/ip6tables，看规则列表
2. fixed
3. 2间接满足了3，直接修改暂时改不好，等pr

**Comment by hkfires** [comment]
关于第一点，我部署h-ui面板的vps有两个接口，一个绑了ipv4地址，一个绑了ipv6地址，看了下源码，是通过ls /sys/class/net | grep -E '^en|^eth'找的接口，刚好我ipv6这个接口不是en或eth开头的，因此没有添加对应的规则，问题就出在这里。
另外一点让我疑惑的是，我通过nft list ruleset查看规则集，显示的是
table inet hui_porthopping {
        chain prerouting {
                type nat hook prerouting priority dstnat; policy accept;
        }
}
并没有具体的规则添加进去，而ipv4是转发成功了的。

**Comment by hkfires** [comment]
> 1. 默认是同时转发ipv4和ipv6，看一下转发工具用的是nft还是iptables/ip6tables，看规则列表
> 2. fixed
> 3. 2间接满足了3，直接修改暂时改不好，等pr

关于第一点，我部署h-ui面板的vps有两个接口，一个绑了ipv4地址，一个绑了ipv6地址，看了下源码，是通过ls /sys/class/net | grep -E '^en|^eth'找的接口，刚好我ipv6这个接口不是en或eth开头的，因此没有添加对应的规则，问题就出在这里。
另外一点让我疑惑的是，我通过nft list ruleset查看规则集，显示的是
table inet hui_porthopping {
chain prerouting {
type nat hook prerouting priority dstnat; policy accept;
}
}
并没有具体的规则添加进去，而ipv4是转发成功了的。

**Comment by jonssonyan** [comment]
端口跳跃优先使用nft，其次使用iptables，只用使用一个
你的ipv6这个接口叫什么名字，做下兼容吧

**Comment by hkfires** [comment]
> 端口跳跃优先使用nft，其次使用iptables，只用使用一个 你的ipv6这个接口叫什么名字，做下兼容吧

我的ipv6是通过hurricane electric的隧道添加的，官方给的默认配置中不同系统中名字都不大一样，我用的默认配置中命名是he-ipv6，根据名字来适配的话也挺麻烦的，保不准有些人会把接口名字改掉。
或许把ls /sys/class/net获取到的接口名，把环回口去掉，其他都添加，适用性更广点吧。

**Comment by hkfires** [comment]
> 端口跳跃优先使用nft，其次使用iptables，只用使用一个

看过源码，确实是有nft就跳过iptables的逻辑判断了，但是我用nft list ruleset查看规则集，只能看到预先建立的hui_porthopping表和type nat hook prerouting priority dstnat; policy accept;，应该添加的其他规则没看到
