### ISSUE TITLE
error while importing account export json file

### ISSUE THREAD

**Issue by b2never** [jonssonyan/h-ui#87]
importing AccountExport-<DATE>.json in Account Manage panel fails when H-UI is freshly installed failed because of duplicate key error

for now you can open the json file and change the id of 1 to anything else to resolve this issue

**Comment by b2never** [comment]
![image](https://github.com/user-attachments/assets/524118fa-d3f2-4e88-8675-93cd2d53c217)

**Comment by jonssonyan** [comment]
The primary key id is repeated

**Comment by b2never** [comment]
i know and as i mentioned when you  install h-ui from scratch it will create a new ADMIN account for you so this one id's will be 1
but when you try to restore the AccountExport JSON file it doesnt get imported because of duplicate key ID (two one at same time)
i still think its a bug and suggest you to delete records from Account table first then import/insert it by json

**Comment by jonssonyan** [comment]
Check whether the imported data user name is repeated

**Comment by jonssonyan** [comment]
Update if exists, add if not
https://github.com/jonssonyan/h-ui/blob/870f5a4bf045116518465ee9ab0400ef02fa3233/dao/account.go#L44C6-L44C19
