### ISSUE TITLE
ACME无法生成 证书

### ISSUE THREAD

**Issue by charliecaiyu** [jonssonyan/h-ui#89]
docker 安装 的， 不知道为什么ACME怎么也生成不了证书在h-ui下面

log如下 

error | 2024-12-01T23:42:01+08:00 [34mINFO[0m server up and running {"listen": ":443"} | 2024-12-01 23:42:01
-- | -- | --
error | 2024-12-01T23:42:01+08:00 [34mINFO[0m traffic stats server up and running {"listen": ":9999"} | 2024-12-01 23:42:01
error | 2024-12-01T23:42:00+08:00 [34mINFO[0m obtain releasing lock {"identifier": "www.xxxxxxx.us.kg"} | 2024-12-01 23:42:00
error | 2024-12-01T23:42:00+08:00 [34mINFO[0m obtain certificate obtained successfully {"identifier": "www.xxxxxxx.us.kg"} | 2024-12-01 23:42:00
error | 2024-12-01T23:42:00+08:00 [34mINFO[0m acme_client successfully downloaded available certificate chains {"count": 1, "first_url": "https://acme.zerossl.com/v2/DV90/cert/jRtQg2NC-rJUrjDuvxIB8A"} | 2024-12-01 23:42:00
error | 2024-12-01T23:41:42+08:00 [34mINFO[0m acme_client validations succeeded; finalizing order {"order": "https://acme.zerossl.com/v2/DV90/order/BsQ_O6eWTl-Wy1kVW2eBNw"} | 2024-12-01 23:41:42
error | 2024-12-01T23:41:42+08:00 [34mINFO[0m acme_client authorization finalized {"identifier": "www.xxxxxxx.us.kg", "authz_status": "valid"} | 2024-12-01 23:41:42
error | 2024-12-01T23:41:37+08:00 [34mINFO[0m served key authentication {"identifier": "www.xxxxxxx.us.kg", "challenge": "http-01", "remote": "91.199.212.132:43126", "distributed": false} | 2024-12-01 23:41:37
error | 2024-12-01T23:41:35+08:00 [34mINFO[0m acme_client trying to solve challenge {"identifier": "www.xxxxxxx.us.kg", "challenge_type": "http-01", "ca": "https://acme.zerossl.com/v2/DV90"} | 2024-12-01 23:41:35

error | 2024-12-01T23:41:34+08:00 [34mINFO[0m done waiting on internal rate limiter {"identifiers": ["www.tradeccd.us.kg"], "ca": "https://acme.zerossl.com/v2/DV90", "account": "123456@163.com"} | 2024-12-01 23:41:34
-- | -- | --
error | 2024-12-01T23:41:34+08:00 [34mINFO[0m waiting on internal rate limiter {"identifiers": ["www.xxxxxxx.us.kg"], "ca": "https://acme.zerossl.com/v2/DV90", "account": "123456@163.com"} | 2024-12-01 23:41:34
error | 2024-12-01T23:41:31+08:00 [34mINFO[0m obtain obtaining certificate {"identifier": "www.xxxxxxx.us.kg"} | 2024-12-01 23:41:31
error | 2024-12-01T23:41:31+08:00 [34mINFO[0m obtain lock acquired {"identifier": "www.xxxxxxx.us.kg"} | 2024-12-01 23:41:31
error | 2024-12-01T23:41:31+08:00 [34mINFO[0m obtain acquiring lock {"identifier": "www.xxxxxxx.us.kg"} | 2024-12-01 23:41:31
error | 2024-12-01T23:41:31+08:00 [34mINFO[0m maintenance started background certificate maintenance {"cache": "0xc000183a40"} | 2024-12-01 23:41:31
error | 2024-12-01T23:41:30+08:00 [34mINFO[0m server mode | 2024-12-01 23:41:30

**Comment by jonssonyan** [comment]
docker 生成的证书在容器里面，需要把它映射到宿主机
acme.dir 可以指定生成证书存放的文件夹

**Comment by charliecaiyu** [comment]
感觉可以考虑把这个目录也映射，
