### ISSUE TITLE
增添用户时设置的登录密码无效 一直密码错误

### ISSUE THREAD

**Issue by shiyi62024** [jonssonyan/h-ui#9]
感谢作者的项目
希望可以解决这个问题 谢谢

**Comment by jonssonyan** [comment]
密码要求是6到32位字母或者数字或者特殊字符!@#$%^&*()_+-=

**Comment by shiyi62024** [comment]
用户名和密码可以成功添加 但在确保是正确的用户名 密码时 尝试登录时会弹出wrong password

**Comment by jonssonyan** [comment]
@shiyi62024 现在单用户，只有管理员可以登录，用户不可以。

**Comment by shiyi62024** [comment]
好的 谢谢
