### ISSUE TITLE
使用nginx时web上下文无法正常使用，以及一个设置时的问题

### ISSUE THREAD

**Issue by Thetail001** [jonssonyan/h-ui#90]
首先有一个设置时的问题，我使用一台新的主机时，准备配置证书准备保存时，结果：
![image](https://github.com/user-attachments/assets/366a5301-94ff-46da-8c2d-e3e0748df864)
这是默认了必须有内容才行吗？默认的“/”甚至不能保存配置。

在另一台配置了nginx的主机上，web上下文设置为 `/hboard` , nginx如下配置：

> 其余内容为普遍的https设置，“/”路径导向的是服务器的其他服务
location /hboard {
    proxy_redirect off;
    proxy_pass https://127.0.0.1:8001
    proxy_http_version 1.1;
    proxy_set_header Host $host;
   }

访问`https://domain/hboard`时，浏览器界面为白屏，控制台报错：

> GET https://domain/assets/index-b83c3cfc.js net::ERR_ABORTED 502 (Bad Gateway)
   GET https://domain/assets/index-e50f3332.css net::ERR_ABORTED 502 (Bad Gateway)

访问https://domain:8001/assets/index-b83c3cfc.js 或者https://domain:8001/assets/index-e50f3332.css 可以正确获得纯代码页面。
访问https://domain/hboard/assets/index-b83c3cfc.js 或者https://domain/hboard/assets/index-e50f3332.css 页面均为：

> {
    "code": 50401,
    "type": "no",
    "message": "unauthorized",
    "data": null
}

使用https://ip地址:8001/hborad 和 https://domain:8001/hborad 访问时一切正常。

目测使用ningx时需要将面板端口改为443才能正常使用，可是机器的443端口一般是给一些主服务用的，虽然这个功能也不是很必须，可是域名的直接访问还是更舒服一些，希望作者大大帮忙看下是我没配置正确还是面板的bug。

**Comment by jonssonyan** [comment]
只要代理跟路径/，/assets不要代理，参考代码里面的逻辑，和上下文功能同理
https://github.com/jonssonyan/h-ui/blob/4824d8ee9b119a02624de2af0b0f5cf40f5c6ac4/frontend/embed.go#L21
多问问GPT

**Comment by Thetail001** [comment]
> /无法保存的问题无法复现啊，建议重装看看，或者新开一个机器在测试看看

![msedge_IuPVGSvcsl](https://github.com/user-attachments/assets/61026dfc-307a-40a5-9f77-a0a0c8ab1074)

又开了一台新机器，还是一样，是因为我用的docker吗？

**Comment by Thetail001** [comment]
> 只要代理跟路径/，/assets不要代理，参考代码里面的逻辑，和上下文功能同理
> 
> https://github.com/jonssonyan/h-ui/blob/4824d8ee9b119a02624de2af0b0f5cf40f5c6ac4/frontend/embed.go#L21
> 
> 
> 多问问GPT

额外配置了：

> 
   location /assets {
    proxy_redirect off;
    proxy_pass https://127.0.0.1:8001;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
   }

   location /hui {
    proxy_redirect off;
    proxy_pass https://127.0.0.1:8001;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
   }

之后可以通过`https://domain/hboard`正常使用了，但是感觉有点怪？

**Comment by jonssonyan** [comment]
> 又开了一台新机器，还是一样，是因为我用的docker吗？

校验上下文输入框的正则表达式，已经改了，release和docker image 替换了，没有发新版

重装或者等下个版本更新，可以解决

**Comment by nanoia** [comment]
> 只要代理跟路径/，/assets不要代理，参考代码里面的逻辑，和上下文功能同理
> 
> https://github.com/jonssonyan/h-ui/blob/4824d8ee9b119a02624de2af0b0f5cf40f5c6ac4/frontend/embed.go#L21
> 
> 
> 多问问GPT

我也遇到了 @Thetail001 提到的 Nginx 子目录问题，需要为  `/assets, /hui` 额外配置子目录，才可通过 `https://domain/hboard` 访问，否则 `/assets, /hui` 路由的请求不会遵循面板中设置的 web 上下文。h-ui 版本：v0.0.14
Nginx片段如下：
```
   # h-ui
   location /hboard {
       proxy_redirect off;
       proxy_pass http://127.0.0.1:10020;
       proxy_http_version 1.1;
       proxy_set_header Host $host;
   }

   # h-ui assets
   location /assets {
       proxy_redirect off;
       proxy_pass http://127.0.0.1:10020;
       proxy_http_version 1.1;
       proxy_set_header Host $host;
   }

   # h-ui hui
   location /hui {
       proxy_redirect off;
       proxy_pass http://127.0.0.1:10020;
       proxy_http_version 1.1;
       proxy_set_header Host $host;
   }
```

> > 只要代理跟路径/，/assets不要代理，参考代码里面的逻辑，和上下文功能同理
> > https://github.com/jonssonyan/h-ui/blob/4824d8ee9b119a02624de2af0b0f5cf40f5c6ac4/frontend/embed.go#L21
> > 
> > 多问问GPT
> 
> 额外配置了：
> 
> > 
> 
> location /assets { proxy_redirect off; proxy_pass https://127.0.0.1:8001; proxy_http_version 1.1; proxy_set_header Host $host; }
> 
> location /hui { proxy_redirect off; proxy_pass https://127.0.0.1:8001; proxy_http_version 1.1; proxy_set_header Host $host; }
> 
> 之后可以通过`https://domain/hboard`正常使用了，但是感觉有点怪？

**Comment by jonssonyan** [comment]
0.0.19 修复了，更新试试
