### ISSUE TITLE
启动hy2报错

### ISSUE THREAD

**Issue by Achordchan** [jonssonyan/h-ui#91]
![image](https://github.com/user-attachments/assets/6ea9c214-d8a8-4c21-9b68-5c9db03af22d)
错误日志如下：<html>
<body>

Hysteria2 OnlineUsers err: Get "http://127.0.0.1:9999/online": dial tcp 127.0.0.1:9999: connect: connection refused
--

</body>
</html>

**Comment by jonssonyan** [comment]
系统日志看看

**Comment by jonssonyan** [comment]
另外第一次启动Hysteria2会有短暂启动失败，原因是正在申请证书，可以在hy2日志里面看到申请状态，持续刷新页面，知道状态显示成功就可以用了
