### ISSUE TITLE
maintenance started background certificate maintenance 

### ISSUE THREAD

**Issue by taraway** [jonssonyan/h-ui#92]
![截屏2024-12-07 凌晨3 25 45](https://github.com/user-attachments/assets/322d7981-253a-4115-94aa-0f84f504cace)

2024-12-07T03:22:38+08:00 [34mINFO[0m maintenance started background certificate maintenance {"cache": "0xc0001058f0"}

提示：开始维护后台证书。

安装配置启动等都正常，节点添加后，却无法连接。

**Comment by jonssonyan** [comment]
Hysteria2状态是不是正常？
服务端配置有没有问题？
客户端配置有没有问题？
服务器地址改成IP，勾选允许不安全，连接看看是否是证书的问题
