### ISSUE TITLE
安装后没有用户名密码

### ISSUE THREAD

**Issue by uedkkk** [jonssonyan/h-ui#93]
你好，我根据readme的方式使用docker完成了安装，文末写到用户名密码为随机6位字符，没太懂这是什么意思？
我现在能够访问面板界面，但是进去之后就是登录界面，此时我并不知道管理员用户名密码是多少，也就一直卡在登录
小白求助

**Comment by fanhuadesenlinnn** [comment]
+1

**Comment by fanhuadesenlinnn** [comment]
Linux do论坛找到账号密码都是sysadmin

**Comment by jonssonyan** [comment]
安装完之后控制台不是会打印系统管理员用户名和密码么？
如果没注意到就用安装脚本里面选项8. Reset sysadmin username and password

早期版本默认用户名和密码是sysadmin，但是很多人没有安全意识，安装好之后没有改默认密码，导致面板被黑，所以现在用户名和密码都是随机6位
